### ISSUE TITLE
output error when I use void* malloc in C

### ISSUE THREAD

**Issue by dragondove** [AtomLinter/linter-gcc#116]
for C language IT is legal to use malloc with void*
like this int * a=malloc(n*sizeof(int));
but linter-gcc output an error when I save.(I know it is illegal in C++).

**Comment by isgj** [comment]
Had the same issue. Go to the settings of the package and change the executable from `g++` to `gcc`. I don't know why the `g++` is used as the default compiler.

**Comment by Wwarrior1** [comment]
It could be fine if it was an additional setting to be able to **switch between `g++` and `gcc`**. Or even better - for `.c` files **automatically** enable `gcc` and for `.cpp` automatically enable `g++`.
