### ISSUE TITLE
installation incomplete, stuck at "Install dependencies for linter gcc"

### ISSUE THREAD

**Issue by madsBR** [AtomLinter/linter-gcc#172]
## Checklist
* [check ] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [ check] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [ ] Ensure that you are using a valid grammar - either C/C++/C++14
* [ check] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

## Issue (including debugging messages):
Everytime i open atom a blue message pops up saying "installing linter-gcc dependencies" when opening console it says there is an error at line 36 view.js
Uncaught TypeError: _this.notificationEl.querySelector is not a function

if it is relevant: I have previously had a few issues due to the fact that i have 2 gcc compilers (one older) in my system) 
Tell me if there is any other info i can provide.

**Comment by adgooden** [comment]
I am also having this issue. I am working with Atom on Windows 10 and have followed all the steps above. I have MinGW installed and included in my $PATH.

**Comment by Fatamos** [comment]
> I am also having this issue. I am working with Atom on Windows 10 and have followed all the steps above. I have MinGW installed and included in my $PATH.

So, did you solve the problem?

**Comment by Arcanemagus** [comment]
Closing this as a duplicate of #209, simply as a place to gather the various reports of this issue together.

**Comment by Arcanemagus** [comment]
Duplicate of #209
