### ISSUE TITLE
The linter-gcc does not point out my errors.

### ISSUE THREAD

**Issue by Lavenderloved** [AtomLinter/linter-gcc#197]
There is a obvious error in the line 4,but there are no tips showing that I am wrong.
![image](https://user-images.githubusercontent.com/43584198/49820660-7c3ac600-fdb3-11e8-9ea2-80f5fa1eb082.png)

**Comment by Otavva** [comment]
I have this issue too!

**Comment by SpeedrunnerG55** [comment]
#199 Check if you are using linter 2.3.0, the last update removed support for the old linter API and this package uses it

**Comment by Otavva** [comment]
Oh! Thank you so much! At now I can use it!

**Comment by Arcanemagus** [comment]
@Otavva it's highly likely you are hitting https://github.com/hebaishi/linter-gcc/issues/199.

**Comment by otbrown** [comment]
As it seems linter-gcc is no longer maintained @tvincent056 has published his fork which is compatible with the updated base linter as [linter-gcc2](https://atom.io/packages/linter-gcc2). See [comment](https://github.com/hebaishi/linter-gcc/pull/185#issuecomment-435928445) on #185

**Comment by Arcanemagus** [comment]
Duplicate of #199
