### ISSUE TITLE
consider this project dead if this issue is not removed (latest commit was on 2017 jan)

### ISSUE THREAD

**Issue by therealadityashankar** [AtomLinter/linter-gcc#207]
## Checklist
* [ ] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [ ] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [ ] Ensure that you are using a valid grammar - either C/C++/C++14
* [ ] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

**Comment by Delran** [comment]
Linter GCC isn't working anymore and probably never will again.
Here's a link to [LinterGCC2](https://atom.io/packages/linter-gcc2) by tvincent056.

**Comment by hebaishi** [comment]
I have transferred ownership of the project to the AtomLinter organization so perhaps someone in that organization can maintain it.

**Comment by Arcanemagus** [comment]
If anyone wants to help maintain this (@tvincent056 ?) please let me know! I don't use this personally so my help will be minimal.
