### ISSUE TITLE
I cant install atom linter gcc.its shows"npm WARN deprecated sb-memoize@1.0.2: No longer maintained - Use lodash probably npm ERR! Unexpected end of JSON input while parsing near '...MGZNbL9YcGBJl4MH4nrxH'  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\stark siv\.atom\.apm\_logs\2020-12-26T17_25_37_936Z-debug.log" A little help is appreciated,♥

### ISSUE THREAD

**Issue by TinkerWizard** [AtomLinter/linter-gcc#223]
## Checklist
* [x] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [x] Ensure that you are using a valid grammar - either C/C++/C++14
* [x] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [ ] Ensure that you have read all the relevant information in the [wiki](https://github.com/hebaishi/linter-gcc/wiki), particularly the [Common Issues](https://github.com/hebaishi/linter-gcc/wiki/Common-Issues) page.

**Comment by hebaishi** [comment]
Please write your issue description in the description box. Not the title.

**Comment by TinkerWizard** [comment]
@hebaishi sorry I wasn't sure. I tried to install atom linter GCC but it throws an error in installation. I don't know what to do.
